import { Injectable } from "@nestjs/common";
import { execFile, spawn } from "child_process";
import { promisify } from "util";
import path from "path";
import { existsSync } from "fs";
import { PrismaService } from "../prisma/prisma.service";
import { CodeWorkspaceService } from "../env-clones/code-workspace.service";
import { CLAUDE_GID } from "../common/repo-base-dir";
import { composeProjectName } from "./compose-naming";
import {
  apiInContainer,
  attachToWithvibe,
  resolveSidecarTarget,
} from "./sidecar-net";
import { InjectPinoLogger, PinoLogger } from "nestjs-pino";

const exec = promisify(execFile);

// Custom image baked from `apps/api/code-server-image/Dockerfile`. Falls back
// to the upstream image if the override env var isn't set; the upstream image
// works fine but won't have the Claude Code extension pre-installed.
// Tag follows the install's WITHVIBE_VERSION (set by `withvibe init`); falls
// back to :latest for from-source installs.
const DEFAULT_IMAGE = `withvibe-code-server:${process.env.WITHVIBE_VERSION || "latest"}`;
const FALLBACK_IMAGE = "codercom/code-server:latest";
const INTERNAL_PORT = 8080;

type StartResult =
  | { ok: true; containerId: string; port: number }
  | { ok: false; error: string };

/**
 * Per-env browser-served VS Code (code-server) sidecar. Same lifecycle shape
 * as DbViewerService / BrowserSidecarService:
 *   - one container per env, attached to the env's compose network
 *   - mounts the env dir as /home/coder/workspace so files are the same files
 *     the agents and the user's local clones see
 *   - opens the multi-root .code-workspace generated by CodeWorkspaceService
 *   - DockerService stops it before `compose down`
 *
 * Auth: the container starts with `--auth=none`. Same trust model as the
 * other sidecars: the published port goes through the API's reverse proxy
 * which already gates on the user's session.
 */
@Injectable()
export class CodeServerService {
  constructor(
    @InjectPinoLogger(CodeServerService.name)
    private readonly logger: PinoLogger,
    private readonly prisma: PrismaService,
    private readonly codeWorkspace: CodeWorkspaceService
  ) {}

  private image(): string {
    return process.env.CODE_SERVER_IMAGE?.trim() || DEFAULT_IMAGE;
  }

  async start(envId: string): Promise<StartResult> {
    const env = await this.prisma.client.env.findUnique({
      where: { id: envId },
      select: {
        id: true,
        title: true,
        workspaceId: true,
        containerStatus: true,
        codeServerContainerId: true,
        codeServerPort: true,
        codeServerStatus: true,
        workspace: { select: { anthropicApiKey: true } },
      },
    });
    if (!env) return { ok: false, error: "Env not found" };

    if (env.containerStatus !== "running") {
      return {
        ok: false,
        error:
          "Env must be running before opening VS Code in the browser — start the env first.",
      };
    }

    // Reuse a still-running container.
    if (env.codeServerContainerId && env.codeServerPort) {
      const alive = await this.containerAlive(env.codeServerContainerId);
      if (alive) {
        return {
          ok: true,
          containerId: env.codeServerContainerId,
          port: env.codeServerPort,
        };
      }
      await this.hardStop(env.codeServerContainerId).catch(() => {});
    }

    const project = composeProjectName(envId);
    const network = await this.findEnvNetwork(project);
    if (!network) {
      return {
        ok: false,
        error: `Could not find the env's compose network (project=${project}). Start the env first so docker-compose creates its network.`,
      };
    }

    // Make sure the .code-workspace exists. EnvCloneService keeps it fresh,
    // but stale envs created before this feature shipped won't have one yet.
    await this.codeWorkspace.writeWorkspaceFiles(envId);

    const envDir = this.codeWorkspace.envDir(env.workspaceId, env.id);
    const wsFile = this.codeWorkspace.workspaceFileName(env.id, env.title);

    await this.prisma.client.env.update({
      where: { id: envId },
      data: {
        codeServerStatus: "starting",
        codeServerError: null,
      },
    });

    const image = await this.resolveImage();
    const anthropicKey = env.workspace?.anthropicApiKey?.trim();

    const dockerArgs = [
      "run",
      "--rm",
      "-d",
      "--network",
      network,
      "--label",
      `com.withvibe.code-server=${envId}`,
      // Bind the env dir so edits in code-server land on the same files
      // the agent + user's env clones see.
      "-v",
      `${envDir}:/home/coder/workspace`,
      // Run as the host user so written files don't end up root-owned.
      // codercom/code-server's entrypoint honours PUID/PGID via gosu.
      "-e",
      `DOCKER_USER=${process.env.USER || "coder"}`,
      // The env dir is created root:CLAUDE_GID mode 02775 and the root api
      // writes the .code-workspace as root:CLAUDE_GID 0664 (see
      // ensureEnvDir). The image runs as `coder` (uid 1000), which is
      // neither root nor in that group, so saving the workspace fails with
      // EACCES on deployed installs. Add the claude group as a supplementary
      // group so `coder` can write the group-writable env-dir files. (The
      // image starts directly as `coder` — no privilege drop — so the
      // docker-added group survives to the code-server process.)
      "--group-add",
      String(CLAUDE_GID),
    ];
    // Inject the workspace's Anthropic key so the Claude Code extension /
    // CLI inside the container picks it up automatically. Skipped silently
    // if the workspace hasn't set one — extension still loads, user just
    // has to sign in manually.
    if (anthropicKey) {
      dockerArgs.push("-e", `ANTHROPIC_API_KEY=${anthropicKey}`);
    }
    dockerArgs.push(
      "-p",
      `127.0.0.1:0:${INTERNAL_PORT}`,
      image,
      "--auth",
      "none",
      "--bind-addr",
      `0.0.0.0:${INTERNAL_PORT}`,
      "--disable-telemetry",
      "--disable-update-check",
      // Open the multi-root workspace by default so all repos appear.
      path.posix.join("/home/coder/workspace", wsFile)
    );

    try {
      const { stdout: cidRaw } = await exec("docker", dockerArgs, {
        timeout: 60_000,
      });
      const containerId = cidRaw.trim();
      if (!containerId) {
        throw new Error("docker run returned empty container id");
      }

      // Join the shared `withvibe` network so a containerized api can reach
      // code-server by IP (the published port is loopback-only — see
      // sidecar-net.ts). Best-effort: dev (api on host) doesn't need it.
      await attachToWithvibe(containerId);

      const port = await this.resolvePublishedPort(containerId);
      if (!port) {
        await this.hardStop(containerId).catch(() => {});
        throw new Error("Failed to resolve code-server published port");
      }

      await this.prisma.client.env.update({
        where: { id: envId },
        data: {
          codeServerContainerId: containerId,
          codeServerPort: port,
          codeServerStatus: "running",
          codeServerError: null,
        },
      });

      this.logger.info(
        `Env ${envId}: started code-server ${containerId.slice(0, 12)} on 127.0.0.1:${port} (image=${image})`
      );
      return { ok: true, containerId, port };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      await this.prisma.client.env.update({
        where: { id: envId },
        data: {
          codeServerContainerId: null,
          codeServerPort: null,
          codeServerStatus: "error",
          codeServerError: msg,
        },
      });
      return { ok: false, error: msg };
    }
  }

  async stop(envId: string): Promise<{ ok: true }> {
    const env = await this.prisma.client.env.findUnique({
      where: { id: envId },
      select: { codeServerContainerId: true },
    });
    if (env?.codeServerContainerId) {
      await this.hardStop(env.codeServerContainerId).catch((err) => {
        this.logger.warn(
          `Env ${envId}: failed to remove code-server ${env.codeServerContainerId}: ${err instanceof Error ? err.message : String(err)}`
        );
      });
    }
    await this.prisma.client.env.update({
      where: { id: envId },
      data: {
        codeServerContainerId: null,
        codeServerPort: null,
        codeServerStatus: "stopped",
        codeServerError: null,
      },
    });
    return { ok: true };
  }

  async stopQuiet(envId: string): Promise<void> {
    await this.stop(envId).catch(() => {});
  }

  /**
   * `host:port` the api can reach the running code-server at, for the
   * reverse proxy. Null if not running. See sidecar-net.ts.
   */
  async getProxyTarget(envId: string): Promise<string | null> {
    const env = await this.prisma.client.env.findUnique({
      where: { id: envId },
      select: {
        codeServerContainerId: true,
        codeServerPort: true,
        codeServerStatus: true,
      },
    });
    return resolveSidecarTarget({
      containerId: env?.codeServerContainerId,
      status: env?.codeServerStatus,
      publishedPort: env?.codeServerPort,
      internalPort: INTERNAL_PORT,
    });
  }

  /**
   * What the controller hands the browser. Deployed (api in a container):
   * the same-origin proxied path — Traefik routes /api/code-server/view/ to
   * the api, which reverse-proxies to the container. Dev (api on host): the
   * direct loopback URL, which already worked and needs no proxy. Null when
   * not running.
   */
  async viewerUrl(envId: string): Promise<string | null> {
    const env = await this.prisma.client.env.findUnique({
      where: { id: envId },
      select: { codeServerPort: true, codeServerStatus: true },
    });
    if (env?.codeServerStatus !== "running") return null;
    if (await apiInContainer()) {
      return `/api/code-server/view/${envId}/`;
    }
    return env.codeServerPort
      ? `http://127.0.0.1:${env.codeServerPort}/`
      : null;
  }

  // In-flight build (so two concurrent "Open in browser" clicks share one
  // build instead of racing two `docker build` invocations).
  private buildInFlight: Promise<string> | null = null;

  /**
   * Resolve the image to run. If the preferred custom image is missing AND
   * we have its Dockerfile checked into the repo, kick off a one-time
   * `docker build` so future clicks are instant. Falls back to the upstream
   * image only if the build also fails (e.g. no network at build time).
   */
  private async resolveImage(): Promise<string> {
    const preferred = this.image();
    if (await this.imageExists(preferred)) return preferred;
    const buildContext = this.findBuildContext();
    if (!buildContext) {
      this.logger.warn(
        `Image ${preferred} not found and no build context — falling back to ${FALLBACK_IMAGE}.`
      );
      return FALLBACK_IMAGE;
    }
    if (!this.buildInFlight) {
      this.buildInFlight = this.buildImage(preferred, buildContext).finally(
        () => {
          this.buildInFlight = null;
        }
      );
    }
    try {
      return await this.buildInFlight;
    } catch (err) {
      this.logger.error(
        `Auto-build of ${preferred} failed (${err instanceof Error ? err.message : String(err)}). Falling back to ${FALLBACK_IMAGE}.`
      );
      return FALLBACK_IMAGE;
    }
  }

  private async imageExists(tag: string): Promise<boolean> {
    try {
      await exec("docker", ["image", "inspect", tag], { timeout: 5_000 });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Walk up from this file looking for `code-server-image/Dockerfile`. Works
   * both in dev (`apps/api/src/docker/...`) and in built dist (`apps/api/dist/...`).
   * Returns null if the build context isn't shipped with this deployment.
   */
  private findBuildContext(): string | null {
    let dir = __dirname;
    for (let i = 0; i < 8; i++) {
      const candidate = path.join(dir, "code-server-image", "Dockerfile");
      if (existsSync(candidate)) return path.dirname(candidate);
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
    return null;
  }

  private buildImage(tag: string, context: string): Promise<string> {
    this.logger.info(
      `Auto-building ${tag} from ${context} — this happens once and may take a couple minutes.`
    );
    return new Promise((resolve, reject) => {
      const child = spawn(
        "docker",
        ["build", "-t", tag, context],
        { stdio: ["ignore", "pipe", "pipe"] }
      );
      child.stdout?.on("data", (b: Buffer) =>
        this.logger.debug(`[build ${tag}] ${b.toString().trim()}`)
      );
      child.stderr?.on("data", (b: Buffer) =>
        this.logger.debug(`[build ${tag}] ${b.toString().trim()}`)
      );
      // Give the build up to 10 min — pulling the base image + apt + node
      // adds up the first time.
      const timer = setTimeout(
        () => {
          try {
            child.kill("SIGTERM");
          } catch {
            // best-effort
          }
        },
        10 * 60 * 1000
      );
      child.on("error", (err) => {
        clearTimeout(timer);
        reject(err);
      });
      child.on("exit", (code) => {
        clearTimeout(timer);
        if (code === 0) {
          this.logger.info(`Built ${tag} successfully.`);
          resolve(tag);
        } else {
          reject(new Error(`docker build exited with code ${code}`));
        }
      });
    });
  }

  private async findEnvNetwork(project: string): Promise<string | null> {
    try {
      const { stdout } = await exec(
        "docker",
        [
          "network",
          "ls",
          "--filter",
          `label=com.docker.compose.project=${project}`,
          "--format",
          "{{.Name}}",
        ],
        { timeout: 10_000 }
      );
      const names = stdout
        .split("\n")
        .map((s) => s.trim())
        .filter(Boolean);
      if (names.length === 0) return null;
      const preferred = names.find((n) => n.endsWith("_default"));
      return preferred || names[0];
    } catch {
      return null;
    }
  }

  private async resolvePublishedPort(containerId: string): Promise<number | null> {
    try {
      const { stdout } = await exec(
        "docker",
        ["port", containerId, String(INTERNAL_PORT)],
        { timeout: 10_000 }
      );
      for (const line of stdout.split("\n")) {
        const match = line.match(/:(\d+)$/);
        if (match) return Number(match[1]);
      }
      return null;
    } catch {
      return null;
    }
  }

  private async containerAlive(containerId: string): Promise<boolean> {
    try {
      const { stdout } = await exec(
        "docker",
        ["inspect", "-f", "{{.State.Running}}", containerId],
        { timeout: 5_000 }
      );
      return stdout.trim() === "true";
    } catch {
      return false;
    }
  }

  private async hardStop(containerId: string): Promise<void> {
    await exec("docker", ["rm", "-f", containerId], { timeout: 30_000 });
  }
}
