import { Injectable } from "@nestjs/common";
import { mkdir } from "fs/promises";
import * as path from "node:path";
import { ensureEnvDir } from "../common/repo-base-dir";
import type {
  AgentDefinition,
  McpSdkServerConfigWithInstance,
} from "@anthropic-ai/claude-agent-sdk";
import {
  positionLabel,
  displayName,
  type DisplayMember,
  type ChatEngine,
} from "@withvibe/db";
import { PrismaService } from "../prisma/prisma.service";
import { EnvCloneService } from "../env-clones/env-clone.service";
import { AgentChatService } from "../agents/agent-chat.service";
import { EnvKnowledgeService } from "./env-knowledge.service";
import { WorkspaceKnowledgeService } from "./workspace-knowledge.service";
import { MemberMemoryService } from "./member-memory.service";
import { HumanQuestionService } from "./human-question.service";
import { MemoryMirrorService } from "./memory-mirror.service";
import { DockerMcpService } from "../docker/docker-mcp.service";
import { ExternalContextMcpService } from "./external-context-mcp.service";
import { PlaywrightMcpService } from "../docker/playwright-mcp.service";
import { BrowserSidecarService } from "../docker/browser-sidecar.service";
import { McpTokenService } from "../mcp-bridge/mcp-token.service";
import type { DetectedDatabase } from "../docker/database-detection";
import {
  parseTemplateVariables,
  type TemplateVariable,
} from "../templates/template.types";
import { InjectPinoLogger, PinoLogger } from "nestjs-pino";

function positionsLabels(positions: string[]): string[] {
  return positions.map(positionLabel);
}

const TOGGLE_TO_SDK_TOOL: Record<string, string> = {
  bash: "Bash",
  read: "Read",
  edit: "Edit",
  write: "Write",
  webFetch: "WebFetch",
  webSearch: "WebSearch",
  grep: "Grep",
  glob: "Glob",
};

function disallowedToolsFromToggles(raw: unknown): string[] {
  if (!raw || typeof raw !== "object") return [];
  const toggles = raw as Record<string, unknown>;
  const out: string[] = [];
  for (const [key, sdkName] of Object.entries(TOGGLE_TO_SDK_TOOL)) {
    if (toggles[key] === false) out.push(sdkName);
  }
  return out;
}

function renderTemplateBlock(args: {
  template: { slug: string; name: string; variables: unknown } | null;
  allocatedPorts: { key: string; hostPort: number }[];
}): string {
  if (!args.template) return "";

  let variables: TemplateVariable[] = [];
  try {
    variables = parseTemplateVariables(args.template.variables);
  } catch {
    // Malformed variables JSON shouldn't block chat — just skip the listing.
    variables = [];
  }
  const portByKey = new Map(args.allocatedPorts.map((p) => [p.key, p.hostPort]));

  const portVars = variables.filter((v) => v.kind === "system-port");
  const userInputVars = variables.filter((v) => v.kind === "user-input");
  const secretVars = variables.filter((v) => v.kind === "secret");
  const defaultVars = variables.filter((v) => v.kind === "default");

  const portLines = portVars
    .map((v) => {
      const port = portByKey.get(v.key);
      return `  - \`\${${v.key}}\` → ${port ?? "(not yet allocated)"}`;
    })
    .join("\n");

  const nonPortList = (label: string, vs: TemplateVariable[]) =>
    vs.length === 0
      ? ""
      : `- **${label}:** ${vs.map((v) => `\`\${${v.key}}\``).join(", ")}\n`;

  return `
## Template-driven env — orchestrator-owned files, hands off

This env was materialized from the **${args.template.name}** template (slug: \`${args.template.slug}\`). The compose file and any asset files containing \`\${UPPER_SNAKE}\` tokens were produced by the orchestrator. A \`.env\` file at the env root (header: \`# Generated by TemplateMaterializerService\`) supplies values to \`docker compose\` at up-time. **Do not inline the placeholders, do not edit \`.env\`, do not rewrite the template-materialized files.** If the user wants to change a value, direct them to **workspace → Settings → Templates**.

### Allocated host ports (unique to this env)

${portLines || "  (none — template has no system-port variables)"}

Inside the compose network services still talk to each other on their container-side ports (e.g. \`mysql:3306\`). The host-port mapping above is only what the user's browser / local tooling uses.

### Resolved variables (by kind)

${nonPortList("Auto-injected", [{ key: "PUBLIC_HOST", kind: "default" } as TemplateVariable])}${nonPortList("User-input (collected at create time)", userInputVars)}${nonPortList("Secrets (from API process env)", secretVars)}${nonPortList("Defaults (static in template)", defaultVars)}
The full \`\${VAR}\` list plus resolved values lives in the \`.env\` file — use \`Read\` if you need to sanity-check what compose is seeing. **Never Edit or Write to it.**
`;
}

type ExtraContextSummary = {
  name: string;
  localPath: string;
  fileCount: number;
};

/**
 * Walk `<envDir>/extracontext/` and return one summary row per top-level
 * subdirectory (folder users uploaded, plus the AI-managed `ai/` folder).
 * Loose files at the root are bucketed under a synthetic `(root files)`
 * row so they still show up in the prompt and as additionalDirectories
 * never include the env root itself.
 */
async function summarizeExtraContext(
  rootAbs: string
): Promise<ExtraContextSummary[]> {
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  let entries: import("node:fs").Dirent[];
  try {
    entries = (await fs.readdir(rootAbs, {
      withFileTypes: true,
      encoding: "utf8",
    })) as import("node:fs").Dirent[];
  } catch {
    return [];
  }
  const out: ExtraContextSummary[] = [];
  let looseFiles = 0;
  for (const e of entries) {
    if (e.name.startsWith(".")) continue;
    if (e.isDirectory()) {
      const dirAbs = path.join(rootAbs, e.name);
      out.push({
        name: e.name,
        localPath: dirAbs,
        fileCount: await countFiles(dirAbs),
      });
    } else if (e.isFile()) {
      looseFiles += 1;
    }
  }
  if (looseFiles > 0) {
    out.push({
      name: "(root files)",
      localPath: rootAbs,
      fileCount: looseFiles,
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

async function countFiles(absDir: string): Promise<number> {
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  const stack: string[] = [absDir];
  let n = 0;
  while (stack.length) {
    const dir = stack.pop()!;
    let entries: import("node:fs").Dirent[];
    try {
      entries = (await fs.readdir(dir, {
        withFileTypes: true,
        encoding: "utf8",
      })) as import("node:fs").Dirent[];
    } catch {
      continue;
    }
    for (const e of entries) {
      if (e.name.startsWith(".")) continue;
      const child = path.join(dir, e.name);
      if (e.isDirectory()) stack.push(child);
      else if (e.isFile()) n += 1;
    }
  }
  return n;
}

function renderServicesBlock(args: {
  envId: string;
  containerPorts: unknown;
  serviceUrls: unknown;
  routingMode: string;
  routingBaseDomain: string | null;
  qaBrowserMode: "sidecar" | "user_browser";
}): string {
  const isObj = (v: unknown): v is Record<string, unknown> =>
    !!v && typeof v === "object" && !Array.isArray(v);
  const isUserBrowser = args.qaBrowserMode === "user_browser";

  // Subdomain routing branch — fires whenever the env is configured for it,
  // regardless of whether `serviceUrls` has been populated yet. Template-
  // materialized envs come in with serviceUrls already filled; ad-hoc envs
  // (no template) get an empty map and the agent has to author its own
  // hostnames. We give it the convention either way.
  if (args.routingMode === "subdomain" && args.routingBaseDomain) {
    const baseDomain = args.routingBaseDomain;
    // The platform's wildcard DNS for the install is *single-label* (e.g.
    // *.<baseDomain> → host IP). Two-label hostnames like
    // svc.env-abc123.<baseDomain> would fail DNS resolution. So the
    // convention is: short envId tag (last 6 chars of the cuid) goes
    // directly under the base domain, with services distinguished by an
    // optional prefix on the same label.
    const shortId = args.envId.slice(-6).toLowerCase();
    const populatedUrls = isObj(args.serviceUrls)
      ? (Object.entries(args.serviceUrls).filter(
          ([, v]) => typeof v === "string"
        ) as [string, string][])
      : [];

    // Pick a "primary" service for the example block. Prefer one already in
    // serviceUrls (template-driven), else `frontend`/`web` if seen in
    // containerPorts, else fall back to the first key of containerPorts.
    let exampleService = "frontend";
    let exampleHost = `${shortId}.${baseDomain}`;
    if (populatedUrls.length > 0) {
      const [svc, url] = populatedUrls[0]!;
      exampleService = svc;
      try {
        exampleHost = new URL(url).host;
      } catch {
        /* keep default */
      }
    } else if (isObj(args.containerPorts)) {
      const keys = Object.keys(args.containerPorts).filter((k) => k !== "web");
      const preferred = keys.find((k) => /^(frontend|web|app|ui)$/i.test(k));
      if (preferred) exampleService = preferred;
      else if (keys[0]) exampleService = keys[0];
    }

    const urlLines = populatedUrls.length > 0
      ? populatedUrls.map(([service, url]) => `- **${service}** → ${url}`)
      : [
          `Convention for this env: \`<service>-${shortId}.${baseDomain}\` for each public service (and just \`${shortId}.${baseDomain}\` is reserved for the env's primary frontend, if you want a shorter URL for the user-facing one).`,
          ``,
          `Example hostnames to use when authoring labels:`,
          `- a \`frontend\`/\`web\` service → \`https://${shortId}.${baseDomain}\``,
          `- an \`api\`/\`backend\` service → \`https://api-${shortId}.${baseDomain}\``,
          `- any other service \`<svc>\` → \`https://<svc>-${shortId}.${baseDomain}\``,
        ];

    return `
## Services reachable in this env

This env uses **subdomain routing** under \`${baseDomain}\`. The platform's Traefik handles TLS termination + Let's Encrypt cert issuance for any hostname under that base domain — you don't run your own Traefik inside the env.

${urlLines.join("\n")}

When driving the QA browser (\`mcp__withvibe-browser__navigate\`), use these public URLs (NOT \`localhost:<port>\`).

### Wiring services into the public URLs (compose authoring)

Those URLs only resolve once a service's container is registered with the platform's Traefik. **Every service that should be publicly reachable needs three things in the compose file:**

1. Joined to the platform's external Traefik network (named \`withvibe\`).
2. Its own Traefik labels block declaring router + backend port (one block per service — do not merge them).
3. Its dev server bound to \`0.0.0.0\` (not \`localhost\` / \`127.0.0.1\`) — otherwise it only listens inside its own netns and Traefik can't reach it. For Vite: \`--host 0.0.0.0\` AND \`server.allowedHosts: true\` in \`vite.config.ts\` (Vite's Host-header check 403s unknown hosts otherwise). For Next.js dev: \`-H 0.0.0.0\`. For Spring Boot: \`server.address=0.0.0.0\` (and \`spring.web.cors.*\` for CORS to the public frontend host). Etc.

**Per-service boilerplate** (repeat for each service that needs a public URL — substitute the service name, the host from above, and the dev server's container port):

\`\`\`yaml
services:
  ${exampleService}:
    # ...your existing config (image, command, volumes, env, depends_on)...
    networks:
      - default       # service's own private network (db, redis, sibling services)
      - withvibe      # platform's Traefik network — must be listed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${exampleService}.rule=Host(\`${exampleHost}\`)"
      - "traefik.http.routers.${exampleService}.entrypoints=websecure"
      - "traefik.http.routers.${exampleService}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${exampleService}.loadbalancer.server.port=<container-port>"

networks:
  default: {}
  withvibe:
    external: true   # the platform created this network at install time;
                     # do NOT redeclare as a regular network
\`\`\`

The cert resolver is named \`letsencrypt\` (configured by the platform installer). The first request to a hostname triggers Let's Encrypt issuance via TLS-ALPN-01 — automatic, no extra config. DNS already points at the platform host via wildcard.

**Important: do NOT use \`ports:\` for public-facing services.** \`ports:\` publishes to the host's port (collides with other envs and the platform itself, and bypasses Traefik's TLS). Only Traefik labels + the \`withvibe\` network. Use \`ports:\` only for genuinely host-local debug exposure (e.g. attaching a SQL client to postgres from your laptop).

If a service does NOT need a public URL (postgres, redis, internal workers), keep it private to \`default\` — don't add the \`withvibe\` network or labels. Exposing extras is a leak, not a feature.
`;
  }

  if (!isObj(args.containerPorts) || Object.keys(args.containerPorts).length === 0) {
    return "";
  }
  const portRows: { internal: number | null; external: number; isWeb: boolean }[] = [];
  for (const [key, val] of Object.entries(args.containerPorts)) {
    if (typeof val !== "number") continue;
    if (key === "web") {
      portRows.push({ internal: null, external: val, isWeb: true });
      continue;
    }
    const m = key.match(/^svc_(\d+)$/);
    portRows.push({
      internal: m ? Number(m[1]) : null,
      external: val,
      isWeb: false,
    });
  }
  const webPort = portRows.find((r) => r.isWeb)?.external;
  const otherPorts = portRows.filter((r) => !r.isWeb);

  const portList = otherPorts
    .map((r) =>
      r.internal !== null
        ? `- container port **${r.internal}** → host **${r.external}**`
        : `- host port **${r.external}**`
    )
    .join("\n");

  // user_browser mode — the agent is driving the user's real Chrome on the
  // host machine. `host.docker.internal` is meaningless from there; always
  // use `localhost:<port>` (or whatever the user types).
  if (isUserBrowser) {
    return `\n## Services reachable in this env

This env publishes services on host loopback ports. The QA browser is the **user's real Chrome on this machine**, so URLs must be what a human would type.

${webPort ? `**Primary web URL**: \`http://localhost:${webPort}\`.\n\n` : ""}**All published ports:**

${portList || "(none — env may still be starting)"}

When the QA agent uses \`mcp__withvibe-browser__navigate\`, **always use \`http://localhost:<host-port>\`**. Never use \`host.docker.internal\` or compose service names — those only resolve inside Docker, and this env's QA browser is running outside Docker.
`;
  }

  // sidecar mode — the agent drives a container, so it needs container-side
  // hostnames.
  return `\n## Services reachable in this env

This env publishes services on host loopback ports. Two perspectives matter:

- **A real user on this machine** opens \`http://localhost:<host-port>\` in their browser.
- **The QA browser sidecar** is a container — \`localhost\` inside it means the container itself, not the host. To reach the env's services from there, use one of:
  - **\`http://host.docker.internal:<host-port>\`** — exact equivalent of what the user types in their browser. Use this when the env's frontend code does same-origin fetches via published ports.
  - **\`http://<compose-service-name>:<container-port>\`** — internal compose DNS. Use this when you want to bypass the host port mapping (e.g., you only need to talk to one service).

${webPort ? `**Primary web URL** (what the user sees at \`localhost:${webPort}\` → from QA browser: \`http://host.docker.internal:${webPort}\`).\n\n` : ""}**All published ports:**

${portList || "(none — env may still be starting)"}

When the QA agent uses \`mcp__withvibe-browser__navigate\`, default to \`host.docker.internal:<port>\` so the URL matches what a real user types — same origin, same fetches, same bugs.
`;
}

function renderDatabasesBlock(raw: unknown): string {
  if (!Array.isArray(raw) || raw.length === 0) return "";
  const dbs = raw as DetectedDatabase[];
  const entries = dbs
    .map((d) => {
      const scheme = d.engine === "postgres" ? "postgres" : "mysql";
      const creds = `${encodeURIComponent(d.user)}${d.password ? `:${encodeURIComponent(d.password)}` : ""}`;
      const dbPath = d.database ? `/${d.database}` : "";
      const internal = `${scheme}://${creds}@${d.service}:${d.internalPort}${dbPath}`;
      const host =
        d.publishedPort !== null
          ? `${scheme}://${creds}@localhost:${d.publishedPort}${dbPath}`
          : null;
      const lines = [
        `- **${d.service}** (${d.engine}) — user \`${d.user}\`${d.password ? `, password \`${d.password}\`` : " (no password)"}${d.database ? `, database \`${d.database}\`` : ""}`,
        `  - Inside compose network: \`${internal}\``,
      ];
      if (host) {
        lines.push(`  - From the host machine: \`${host}\``);
      } else {
        lines.push(
          `  - Not exposed to the host — only reachable from inside the compose network. To connect from a local DB client, add a \`ports:\` entry to the compose service.`
        );
      }
      return lines.join("\n");
    })
    .join("\n");
  return `\n## Databases in this env\n\nAuto-detected from the env's compose file at last start/rebuild. Users can inspect these via the **Database** tab in the env UI (opens an embedded Adminer viewer) or connect directly with their own DB client using the URLs below.\n\n${entries}\n`;
}

export type ChatContext = {
  systemAppend: string;
  /** Markdown header (e.g. `**Speaker:** Alice — Engineer`) prepended to every outgoing user message so resumed sessions retain speaker attribution across turns. */
  speakerHeader: string;
  cwd: string;
  additionalDirectories: string[];
  anthropicApiKey: string | null;
  mcpServers: Record<string, McpSdkServerConfigWithInstance>;
  extraAllowedTools: string[];
  disallowedTools: string[];
  /** Sub-agents available to the orchestrator (main chat without a bound agent). */
  subagents: Record<string, AgentDefinition>;
  /** True iff we materialized skills into .claude/skills for any agent this turn. */
  hasSkills: boolean;
  agent: {
    agentId: string;
  } | null;
  /** Workspace-level debug mode — enables extra SDK event logging + UI debug panel. */
  debugMode: boolean;
  /** Env-level engine selector — agent_sdk (in-process) vs. claude_code (runner container). */
  chatEngine: ChatEngine;
  /** Per-env model override ("auto" | concrete model id | null = inherit). */
  envModelChoice: string | null;
  /** Workspace default model ("auto" | concrete model id). */
  workspaceDefaultModel: string;
  /**
   * Short-lived bearer token the Claude Code runner container presents when
   * calling /api/mcp/:serverName. Always minted — even for the Agent SDK
   * engine — so callers can flip engines without rebuilding context.
   */
  mcpBridgeToken: string;
  /** Env + session identity — the Claude Code engine uses these to load + persist `claudeSessionId`. */
  envId: string;
  workspaceId: string;
  sessionId: string | null;
};

@Injectable()
export class ChatContextService {
  constructor(
    @InjectPinoLogger(ChatContextService.name)
    private readonly logger: PinoLogger,
    private readonly prisma: PrismaService,
    private readonly envClones: EnvCloneService,
    private readonly agentChat: AgentChatService,
    private readonly envKnowledge: EnvKnowledgeService,
    private readonly workspaceKnowledge: WorkspaceKnowledgeService,
    private readonly memberMemory: MemberMemoryService,
    private readonly humanQuestion: HumanQuestionService,
    private readonly memoryMirror: MemoryMirrorService,
    private readonly dockerMcp: DockerMcpService,
    private readonly externalContextMcp: ExternalContextMcpService,
    private readonly playwrightMcp: PlaywrightMcpService,
    private readonly browserSidecar: BrowserSidecarService,
    private readonly mcpTokens: McpTokenService
  ) {}

  async build(
    envId: string,
    speakerUserId: string,
    sessionId: string | null = null
  ): Promise<ChatContext> {
    const buildStart = Date.now();
    const phase = async <T>(label: string, fn: () => Promise<T>): Promise<T> => {
      const t0 = Date.now();
      try {
        return await fn();
      } finally {
        this.logger.info(
          `[ctx-build] ${label} took ${Date.now() - t0}ms (env=${envId})`
        );
      }
    };

    const env = await phase("fetch-env", () =>
      this.prisma.client.env.findUnique({
        where: { id: envId },
        include: {
          workspace: true,
          envRepos: { include: { repo: { include: { clone: true } } } },
          template: {
            select: { slug: true, name: true, variables: true },
          },
          allocatedPorts: {
            select: { key: true, hostPort: true },
            orderBy: { key: "asc" },
          },
        },
      })
    );
    if (!env) throw new Error("Env not found");

    const members = await phase("fetch-members", () =>
      this.prisma.client.workspaceMember.findMany({
        where: { workspaceId: env.workspaceId },
        include: {
          user: {
            select: {
              id: true,
              name: true,
              email: true,
              positions: true,
              bio: true,
            },
          },
        },
      })
    );

    const speakerMember = members.find((m) => m.userId === speakerUserId);
    const speakerName =
      speakerMember?.user.name || speakerMember?.user.email || "Unknown";
    const otherMembers = members.filter((m) => m.userId !== speakerUserId);

    const displayScope: DisplayMember[] = members.map((m) => ({
      userId: m.userId,
      name: m.user.name,
      email: m.user.email,
    }));
    const displayNameFor = (userId: string, name: string | null, email: string) =>
      displayName({ userId, name, email }, displayScope);

    // History across turns is now owned by the Agent SDK via `resume:`. We no
    // longer flatten the transcript into the system prompt or maintain our own
    // summary rows — the SDK's built-in compaction handles long sessions.
    const workspaceApiKey =
      env.workspace.anthropicApiKey ?? process.env.ANTHROPIC_API_KEY ?? null;

    const envDir = this.envClones.envDir(env.workspaceId, env.id);
    await phase("mkdir-env-dir", () => ensureEnvDir(envDir));
    // AI deliverables convention: anything the AI produces for the user
    // (reports, PDFs, generated docs) goes here. Plain subfolder of the
    // user-facing extracontext/ tree — users can also write/delete here,
    // it's just a documented landing pad.
    const aiDeliverablesDir = path.join(envDir, "extracontext", "ai");
    await phase("mkdir-extracontext-ai", () =>
      mkdir(aiDeliverablesDir, { recursive: true }).then(() => undefined)
    );

    // Always-on MCP servers: workspace-knowledge + env-knowledge + docker.
    // member-memory and agent-skill are attached conditionally below —
    // non-owner clone sessions get neither (consumers don't train clones).
    const mcpServers: ChatContext["mcpServers"] = {
      "withvibe-workspace": this.workspaceKnowledge.createMcpServer(
        env.workspaceId
      ),
      "withvibe-env": this.envKnowledge.createMcpServer(envId),
      "withvibe-docker": this.dockerMcp.createMcpServer(envId),
      "withvibe-external-context": this.externalContextMcp.createMcpServer(
        env.workspaceId,
        envId
      ),
    };
    const extraAllowedTools: string[] = [
      "mcp__withvibe-workspace__save_workspace_knowledge",
      "mcp__withvibe-env__save_env_knowledge",
      "mcp__withvibe-docker__start_env",
      "mcp__withvibe-docker__stop_env",
      "mcp__withvibe-docker__rebuild_env",
      "mcp__withvibe-docker__get_env_status",
      "mcp__withvibe-docker__wait_for_env_status",
      "mcp__withvibe-docker__get_env_logs",
      "mcp__withvibe-external-context__render_pdf",
    ];

    // Agent persona + skill materialization + MCP server for save_skill.
    let agentBlock = "";
    let agentConfig: ChatContext["agent"] = null;
    // Blanket-block scheduling-style tools. The claude_code preset surfaces a
    // few tools (ScheduleWakeup, CronCreate, etc.) that only work in an
    // interactive Claude Code CLI with a runtime scheduler; our backend
    // invokes query() per-turn so those calls end the turn silently and
    // strand the user. Everything must happen within one turn — the
    // docker-mcp wait_for_env_status tool covers long-running work.
    const disallowedTools: string[] = [
      "ScheduleWakeup",
      "CronCreate",
      "CronDelete",
      "CronList",
      "Monitor",
      "TaskOutput",
      "TaskStop",
      "RemoteTrigger",
      "PushNotification",
    ];
    const subagents: Record<string, AgentDefinition> = {};
    let hasSkills = false;
    // Clone context tracking — used to:
    //   1) gate save_skill + save_member_memory for non-owner clone sessions
    //   2) render the clone owner's memory block
    //   3) tell the FS mirror to include the owner's memory dir
    let cloneOwnerUserId: string | null = null;
    let isNonOwnerCloneSession = false;
    if (sessionId) {
      const session = await phase("fetch-session-agent", () =>
        this.prisma.client.chatSession.findUnique({
          where: { id: sessionId },
          select: {
            agentId: true,
            agent: {
              select: {
                id: true,
                slug: true,
                name: true,
                description: true,
                systemPrompt: true,
                toolToggles: true,
                kind: true,
                cloneForUserId: true,
                cloneForUser: {
                  select: { id: true, name: true, email: true },
                },
              },
            },
          },
        })
      );
      if (session?.agent) {
        const isClone =
          session.agent.kind === "member_clone" &&
          !!session.agent.cloneForUserId;
        cloneOwnerUserId = isClone ? session.agent.cloneForUserId : null;
        isNonOwnerCloneSession =
          isClone && session.agent.cloneForUserId !== speakerUserId;

        for (const sdkName of disallowedToolsFromToggles(
          session.agent.toolToggles
        )) {
          disallowedTools.push(sdkName);
        }
        const skills = await phase("load-agent-skills", () =>
          this.agentChat.loadApplicableSkills(session.agent!.id, envId)
        );
        await phase("materialize-agent-skills", () =>
          this.agentChat.materializeSkills(envDir, skills)
        );
        if (skills.length > 0) hasSkills = true;
        // Render skills inline so they're part of the agent's active persona,
        // not just lazy-invocable via the Skill tool. Short-content skills
        // get their full body; longer ones show description + a pointer.
        const skillsBlock =
          skills.length === 0
            ? ""
            : `\n\n## Your saved rules & skills\n\nApply these **only when they're actually relevant to what the user is asking**. Do NOT dump them unprompted — if the user says "hi", just greet them. If the user asks a question the rule genuinely applies to, then follow it. Use judgment.\n\n${skills
                .map((s) => {
                  const whenLine = `_When: ${s.description}_`;
                  const body =
                    s.content.length <= 600
                      ? s.content
                      : `${s.content.slice(0, 600).trimEnd()}…\n\n(Full body available via the Skill tool: \`${s.slug}\`.)`;
                  return `### ${s.name}\n${whenLine}\n\n${body}`;
                })
                .join("\n\n")}\n`;
        agentBlock = `\n\n# Agent persona — ${session.agent.name}\n\n${session.agent.systemPrompt}${skillsBlock}\n`;

        // save_skill is only available to the clone's OWNER (or any regular
        // agent session). Non-owner clone sessions are consumption-only for
        // clone state.
        if (!isNonOwnerCloneSession) {
          mcpServers["withvibe-agent"] = this.agentChat.createAgentMcpServer({
            agentId: session.agent.id,
            envId,
            envDir,
          });
          extraAllowedTools.push("Skill", "mcp__withvibe-agent__save_skill");
        }

        // QA agent: attach the Playwright MCP server. The MCP server picks the
        // right transport at tool-call time based on env.qaBrowserMode:
        //   - "sidecar": connects via CDP to the Docker QA browser sidecar.
        //     Pre-warm the sidecar here so the first tool call doesn't pay the
        //     boot latency (best-effort; chat still proceeds if it fails).
        //   - "user_browser": dispatches each call to the speaker's paired
        //     Chrome extension. No server-side warm-up needed; if the user
        //     hasn't paired yet, the first tool call surfaces a clear error.
        if (session.agent.slug === "qa") {
          mcpServers["withvibe-browser"] = this.playwrightMcp.createMcpServer({
            envId,
            userId: speakerUserId,
          });
          extraAllowedTools.push(...this.playwrightMcp.allowedToolNames());
          if (env.qaBrowserMode !== "user_browser") {
            await phase("ensure-qa-browser", async () => {
              const result = await this.browserSidecar.start(envId);
              if (!result.ok) {
                this.logger.warn(
                  `QA sidecar not started for env ${envId}: ${result.error}`
                );
              }
            });
          }
        }

        // ask_human target: clone owner for clones, current speaker otherwise.
        const askedOfUserId = isClone
          ? session.agent.cloneForUserId!
          : speakerUserId;
        const askedOfMember = members.find((m) => m.userId === askedOfUserId);
        const askedOfDisplayName = isClone
          ? session.agent.cloneForUser?.name ||
            session.agent.cloneForUser?.email ||
            "the clone owner"
          : askedOfMember
            ? displayNameFor(
                askedOfMember.userId,
                askedOfMember.user.name,
                askedOfMember.user.email
              )
            : speakerName;
        mcpServers["withvibe-human"] = this.humanQuestion.createMcpServer({
          agentId: session.agent.id,
          workspaceId: env.workspaceId,
          askedOfUserId,
          askerUserId: speakerUserId,
          sessionId,
          envId,
          targetDisplayName: askedOfDisplayName,
        });
        extraAllowedTools.push("mcp__withvibe-human__ask_human");

        agentConfig = { agentId: session.agent.id };
      }
    }

    // Attach member-memory MCP (save_member_memory → current speaker)
    // UNLESS this is a non-owner clone session. Non-owners are consumers;
    // writing personal memory while chatting with someone else's clone feels
    // scope-confused, and we want clones trainable only by their owner.
    if (!isNonOwnerCloneSession) {
      mcpServers["withvibe-member"] = this.memberMemory.createMcpServer(
        speakerUserId,
        env.workspaceId
      );
      extraAllowedTools.push("mcp__withvibe-member__save_member_memory");
    }

    // Orchestrator mode (no agent binding): expose workspace agents as
    // sub-agents via the SDK's Agent tool. Each sub-agent gets its own
    // persona + tool restrictions + skills (dir-prefixed to avoid collisions).
    if (!agentConfig) {
      const disabledRows = await phase("fetch-env-disabled-agents", () =>
        this.prisma.client.envAgentDisabled.findMany({
          where: { envId },
          select: { agentId: true },
        })
      );
      const disabledSet = new Set(disabledRows.map((r) => r.agentId));
      const candidates = await phase("fetch-workspace-agents", () =>
        this.prisma.client.agent.findMany({
          where: { workspaceId: env.workspaceId },
          orderBy: [
            { pinned: "desc" },
            { position: "asc" },
            { createdAt: "asc" },
          ],
          select: {
            id: true,
            slug: true,
            description: true,
            systemPrompt: true,
            toolToggles: true,
          },
        })
      );
      const enabled = candidates.filter((a) => !disabledSet.has(a.id));

      if (enabled.length > 0) {
        const perAgent = await phase("load-subagent-skills", () =>
          Promise.all(
            enabled.map(async (a) => ({
              agentSlug: a.slug,
              skills: await this.agentChat.loadApplicableSkills(a.id, envId),
            }))
          )
        );
        const skillMap = await phase("materialize-subagent-skills", () =>
          this.agentChat.materializeSkillsForManyAgents(envDir, perAgent)
        );
        const totalSkills = Object.values(skillMap).reduce(
          (acc, arr) => acc + arr.length,
          0
        );
        if (totalSkills > 0) hasSkills = true;

        for (const a of enabled) {
          const disallowed = disallowedToolsFromToggles(a.toolToggles);
          subagents[a.slug] = {
            description: a.description,
            prompt: a.systemPrompt,
            ...(disallowed.length > 0 && { disallowedTools: disallowed }),
            skills: skillMap[a.slug] ?? [],
          };
        }
      }
    }

    const workspaceKnowledgeRows = await phase("load-workspace-knowledge", () =>
      this.workspaceKnowledge.load(env.workspaceId)
    );
    const workspaceKnowledgeBlock = workspaceKnowledgeRows.length
      ? workspaceKnowledgeRows
          .map((k) => `- **${k.title}** — ${k.description}\n  ${k.content.replace(/\n/g, "\n  ")}`)
          .join("\n")
      : "(none yet — save cross-env facts with `save_workspace_knowledge` when you learn something team-wide that applies across every env)";

    const envKnowledgeRows = await phase("load-env-knowledge", () =>
      this.envKnowledge.load(envId)
    );
    const envKnowledgeBlock = envKnowledgeRows.length
      ? envKnowledgeRows
          .map((k) => `- **${k.title}** — ${k.description}\n  ${k.content.replace(/\n/g, "\n  ")}`)
          .join("\n")
      : "(none yet — save env-specific facts with `save_env_knowledge` when something only applies to THIS env — not team rules)";

    const memberMemoryRows = await phase("load-member-memory", () =>
      this.memberMemory.load(speakerUserId, env.workspaceId)
    );
    const memberMemoryBlock = memberMemoryRows.length
      ? memberMemoryRows
          .map((m) => `- **${m.title}** — ${m.description}\n  ${m.content.replace(/\n/g, "\n  ")}`)
          .join("\n")
      : "(none yet — save private notes about this speaker with `save_member_memory` when you learn something worth remembering next time)";

    // For non-owner clone sessions, also load the clone owner's memory so the
    // clone can embody them. READ-ONLY here — only the owner writes.
    const cloneOwnerMember =
      cloneOwnerUserId && cloneOwnerUserId !== speakerUserId
        ? members.find((m) => m.userId === cloneOwnerUserId)
        : null;
    const cloneOwnerMemoryRows = cloneOwnerMember
      ? await phase("load-clone-owner-memory", () =>
          this.memberMemory.load(cloneOwnerMember.userId, env.workspaceId)
        )
      : [];
    const cloneOwnerDisplayName = cloneOwnerMember
      ? displayNameFor(
          cloneOwnerMember.userId,
          cloneOwnerMember.user.name,
          cloneOwnerMember.user.email
        )
      : null;
    const cloneOwnerMemoryBlock =
      cloneOwnerMember && cloneOwnerMemoryRows.length
        ? cloneOwnerMemoryRows
            .map(
              (m) =>
                `- **${m.title}** — ${m.description}\n  ${m.content.replace(/\n/g, "\n  ")}`
            )
            .join("\n")
        : cloneOwnerMember
          ? "(no notes yet about the clone owner)"
          : "";

    // Ensure an env clone for each attached repo so AI edits land on env branch.
    const readyRepos: {
      name: string;
      url: string;
      localPath: string;
      branch: string;
    }[] = [];
    await phase("ensure-env-clones", async () => {
      for (const er of env.envRepos) {
        if (er.repo.clone?.cloneStatus !== "ready") continue;
        const res = await this.envClones.ensureEnvClone(er.id);
        if ("error" in res) continue;
        readyRepos.push({
          name: er.repo.name,
          url: er.repo.url,
          localPath: res.localPath,
          branch: res.branch,
        });
      }
    });

    const reposBlock =
      readyRepos.length > 0
        ? readyRepos
            .map(
              (r) =>
                `- ${r.name} (${r.branch}) — ${r.url}\n  Local path: ${r.localPath}`
            )
            .join("\n")
        : "(no repositories attached to this env)";

    // Extra-context tree — scan `<envDir>/extracontext/` directly. Disk is the
    // single source of truth (no Attachment metadata table). The AI's own
    // deliverables convention-folder (`extracontext/ai/`) is just another
    // child here.
    const extraContext = await summarizeExtraContext(
      path.join(envDir, "extracontext")
    );
    const extraContextBlock =
      extraContext.length > 0
        ? extraContext
            .map(
              (c) =>
                `- ${c.name}/ (${c.fileCount} file${c.fileCount === 1 ? "" : "s"}) — ${c.localPath}`
            )
            .join("\n")
        : "(no extra context yet — user can upload from the Extra Context tab; AI deliverables land under ./extracontext/ai/)";

    const teamBlock =
      otherMembers
        .map((m) => {
          const display = displayNameFor(
            m.userId,
            m.user.name,
            m.user.email
          );
          const email = m.user.email;
          const posLabels = positionsLabels(m.user.positions);
          const pos = posLabels.length ? ` — ${posLabels.join(", ")}` : "";
          const bioLine = m.user.bio ? `\n    About: ${m.user.bio}` : "";
          return `- ${display} <${email}>${pos}${bioLine}`;
        })
        .join("\n") || "(you are the only member)";

    const speakerPosLabels = positionsLabels(
      speakerMember?.user.positions ?? []
    );
    const speakerEmail = speakerMember?.user.email ?? "";
    const speakerBio = speakerMember?.user.bio ?? "";
    const speakerDisplay = speakerMember
      ? displayNameFor(
          speakerMember.userId,
          speakerMember.user.name,
          speakerMember.user.email
        )
      : speakerName;

    const speakerHeader = speakerPosLabels.length
      ? `**Speaker:** ${speakerDisplay} — ${speakerPosLabels.join(", ")}`
      : `**Speaker:** ${speakerDisplay}`;

    const systemAppend = `# Workspace context

You are the AI collaborator for an R&D team using a shared workspace called "${env.workspace.name}".${
      env.workspace.description
        ? `\nWorkspace description: ${env.workspace.description}`
        : ""
    }

## Current speaker — who you are talking to right now

Display name: ${speakerDisplay}
Full name: ${speakerName}
Email: ${speakerEmail || "(not specified)"}
Position: ${speakerPosLabels.length ? speakerPosLabels.join(", ") : "(not specified)"}
About: ${speakerBio || "(not specified)"}

When you respond, address ${speakerDisplay} directly. Tailor your tone and depth to their position(s) and what they've shared about themselves.

## Private notes about ${speakerDisplay} (private to them — teammates don't see this)

Private memory you've accumulated about this speaker across past sessions. Use this to tailor how you work with them.${
      isNonOwnerCloneSession
        ? " **Note:** in this clone session `save_member_memory` is disabled — only the clone owner can train the clone."
        : " When you learn something new worth remembering next time, save it with `save_member_memory` (no permission needed)."
    } Never expose these notes to other teammates. For team-wide facts, use \`save_workspace_knowledge\` instead.

${memberMemoryBlock}${
      cloneOwnerDisplayName
        ? `\n\n## About the person you're a clone of — ${cloneOwnerDisplayName} (READ-ONLY in this session)\n\nYou are an AI clone of ${cloneOwnerDisplayName}. These are their private notes — read them to embody them properly. You cannot save here; only ${cloneOwnerDisplayName} can. If you need their input on something, use \`ask_human\`.\n\n${cloneOwnerMemoryBlock}`
        : ""
    }

## How to identify team members

Each teammate below has a **display name** (which may be "First L." when multiple teammates share a first name) and an **email** (always unique). If the speaker refers to a teammate by first name and that name is ambiguous across the team, ask which teammate they mean — confirm via email if helpful.

## Other team members on this env

${teamBlock}

## Current env

Title: ${env.title}
Status: ${env.status}
${env.description ? `Description: ${env.description}` : ""}

## Workspace knowledge (cross-env, team-wide)

Facts about the team, company, product, and conventions that apply in EVERY env in this workspace. Treat as ground truth. When you learn something new that applies team-wide — NOT just to this env — save it with \`save_workspace_knowledge\`. Prefer this tier over env-knowledge whenever the fact isn't tied to this specific env. Do NOT save anything private to the current speaker here.

${workspaceKnowledgeBlock}

## Env knowledge (specific to this env)

Facts scoped to THIS env only: ports, local services, setup quirks, this env's repos. Use \`save_env_knowledge\` only when the fact wouldn't make sense in another env — otherwise prefer \`save_workspace_knowledge\`.

${envKnowledgeBlock}

## Repositories attached to this env

Each repo is checked out as its own per-env clone on a per-env branch. The branch is named \`env/<title-slug>-<shortId>\` and was created off the base branch the user selected at env-creation time. Your edits live on this branch — they do not touch the shared main clone, and they are NOT auto-committed or pushed. Mention to the user when you make changes.

${reposBlock}

## Extra context attached to this env

User-uploaded folders/files that are NOT part of the env's runtime/compose. They live at \`./extracontext/<name>/\` (sibling of repos). Treat them as reference material the user wants you to read and, when relevant, draw from when implementing changes in this env. You may modify these files if the task calls for it.

${extraContextBlock}

## AI deliverables — \`./extracontext/ai/\`

When the user asks you to produce a **deliverable artifact** — a technical document about this env, a report, a spec, a diagram, an exported dataset — save it under \`./extracontext/ai/\` (a subfolder of the Extra Context above). Use \`Write\` to create files; use subfolders freely to organize (e.g. \`./extracontext/ai/docs/architecture.md\`, \`./extracontext/ai/reports/2026-Q2-summary.md\`). Pick descriptive filenames.

This folder is **shared across all agents in this env** and shows up in the user's Extra Context tab where they can browse, download, edit, and delete. The user can modify or remove these files freely — do not assume what you saved last turn is still there. Do NOT use this for scratch notes or intermediate work; only finished artifacts the user asked for.

Match the format the user requested (\`.md\` for documents, \`.csv\` for tabular data, \`.json\` for structured data, \`.html\`/\`.svg\` when they ask for visuals, etc.).

**PDFs:** \`Write\` the markdown source first (e.g. \`./extracontext/ai/docs/architecture.md\`), then call the \`mcp__withvibe-external-context__render_pdf\` tool with \`sourcePath\` + \`outputPath\` (both inside \`./extracontext/\`, output ending in \`.pdf\`). Keep the \`.md\` next to the PDF — the user may want both. The tool runs server-side via headless Chromium.

Your current working directory is the **env root** — repos sit as sibling subdirectories (e.g. \`./${readyRepos[0]?.name ?? "repo-name"}\`).

You can use Read, Grep, Glob, Edit, Write, and Bash tools against these repository paths.
${renderTemplateBlock({ template: env.template, allocatedPorts: env.allocatedPorts })}${renderServicesBlock({ envId: env.id, containerPorts: env.containerPorts, serviceUrls: env.serviceUrls, routingMode: env.routingMode, routingBaseDomain: env.routingBaseDomain, qaBrowserMode: env.qaBrowserMode })}${renderDatabasesBlock(env.detectedDatabases)}
## Running the environment (docker-compose)

This env has **Start / Stop / Rebuild** buttons in the UI that invoke \`docker compose\`. The system picks the compose file in this priority:

1. A custom compose YAML the user pasted into the env's Compose dialog (override)
2. A \`docker-compose.yml\` / \`compose.yaml\` at the **env root** (your cwd)
3. A compose file inside one of the attached repo clones

**When you generate or update a compose file, write it to the env root** (\`./docker-compose.yml\` relative to your cwd). All attached repos can be referenced as siblings (\`./${readyRepos[0]?.name ?? "repo-a"}\`, etc.).

### CRITICAL: generate dev-style compose, not prod-style

The whole point of this env is rapid iteration — the user (and you) edit files and expect changes to show up without a full container rebuild. **Always generate a dev-style compose** that bind-mounts source code into the container and runs the framework's dev server (with file watching / HMR).

Prod-style (copy source into image, \`npm run build\`, serve static output) forces a rebuild on every edit. Do NOT generate that unless the stack genuinely has no dev-server option.

**Dev-style recipes:** see the built-in DevOps agent's skills for Node/Vite, Python, Java/Spring, and database services — those are materialized as \`.claude/skills/*/SKILL.md\` files and Claude can auto-invoke them.

### Iterate until it actually runs — use the docker MCP tools, not Bash

You have in-process MCP tools that drive the exact same lifecycle the user's Start / Stop / Rebuild buttons do. **Always use these instead of shelling out to \`docker compose\`** — a Bash \`docker compose up\` reads the same \`.env\` as Start and will fight for the same host ports. Tools:

- \`start_env\` — same as the Start button. Returns immediately; work runs in the background and writes to the log buffer.
- \`stop_env\` — same as the Stop button.
- \`rebuild_env\` — same as the Rebuild button (compose down + up --build).
- \`wait_for_env_status\` — **blocks server-side** until status transitions to \`running\` / \`error\` (or a custom target), or a timeout elapses. Use this instead of busy-polling \`get_env_status\`.
- \`get_env_status\` — one-shot status snapshot (use sparingly; \`wait_for_env_status\` is almost always the right tool).
- \`get_env_logs\` — tail of the env's log buffer (the same stream the UI log panel shows the user).

### CRITICAL: you have ONE turn. There is no scheduler.

You're running inside a single chat turn. **There is no "come back later", no wake-up, no cron.** Do NOT call any tool that sounds like \`ScheduleWakeup\`, \`CronCreate\`, or similar — they don't exist in your runtime, and calling them means the turn ends with the user stranded. You must reach a terminal status (\`running\` or \`error\`) or explicitly hand back to the user before you stop speaking.

Long-running builds (mvn package, cold npm install) can take 5–10 minutes. Cover that by calling \`wait_for_env_status\` in a loop, **with a short text update to the user between each call** so they see progress:

\`\`\`
(emit: "Starting the env…")
→ start_env
→ wait_for_env_status({ timeoutSec: 90 })
  - if running / error → done polling, go to step below
  - if timed out → (emit: "Still building — ~90s in. Polling again.") → wait_for_env_status again
→ repeat
\`\`\`

Keep each \`wait_for_env_status\` call at \`timeoutSec: 60–120\` and repeat as needed. Emit a brief update between polls (one short sentence — don't spam). Give up after ~10 minutes of transitional status with no progress in logs and hand back to the user with a concise diagnostic.

### The loop

1. Call \`rebuild_env\` (or \`start_env\` if nothing is running yet).
2. Loop: \`wait_for_env_status({ timeoutSec: 90 })\` → short text update → repeat until it returns \`running\` or \`error\`.
3. On \`error\`: call \`get_env_logs\` (bump \`maxChars\` if truncated). Diagnose. Fix the file if the fix is clearly yours to make. Back to step 1.
4. Once \`running\`, verify hot reload: edit a file in \`./<repo>/src/...\`, call \`get_env_logs\` again, look for "updated" / "HMR" / dev-server reload message.
5. Only then tell the user "the env is up — your edits now take effect live and you won't need to Rebuild for source changes (only compose / Dockerfile changes themselves)".

Common fixes: dev server binding to \`localhost\` instead of \`0.0.0.0\`, wrong port, missing file-watch env var on macOS (\`CHOKIDAR_USEPOLLING=true\` or \`WATCHPACK_POLLING=true\`), \`npm install\` failing on lockfile mismatch.

**If the same error recurs 2–3 times** (missing credentials, ambiguous requirements, needs a human decision): stop iterating, describe the problem concisely in chat, and ask the speaker a focused question. Don't grind retries that can't succeed without input.

## Surveying code before changes — delegate to \`Task\`

When the user asks you to plan, audit, refactor, survey, "look at the codebase before doing X," or anything where you'd otherwise issue 5+ \`Read\`/\`Grep\`/\`Glob\`/\`Bash\` calls to map the surface area before deciding what to change — **use the \`Task\` tool with \`general-purpose\` (or a matching specialist agent if one exists for the domain) instead of doing the exploration inline.**

Why this matters: each inline tool call costs ~2–4 seconds of API round-trip overhead before the model resumes its next sub-turn. Seven sequential greps cost ~20 seconds of pure latency for what could be one parallel sub-agent call. The \`Task\` subagent runs in its own conversation, can fan out parallel reads/greps inside a single one of its sub-turns, and returns a single synthesized summary. You stay focused on the actual planning instead of file-by-file reading.

**When NOT to use \`Task\`:**
- Single-file edits or quick lookups (one \`Read\` or one \`Grep\` is fine inline).
- Sequential exploration where each step's input genuinely depends on the previous step's output (rare in practice — most "I'll grep, then read, then grep again" sequences could have been one parallel call).
- The modification work itself — \`Task\` is for read-only investigation. Do edits in your own turn after the survey returns.

**When you DO call tools inline** (small reads, follow-up confirmations, the actual edits): **batch independent calls into a single sub-turn with parallel \`tool_use\` blocks.** Do not issue them one at a time and "think between" each — that's the same ~3s/turn cost stacking up. If you find yourself about to issue your second consecutive \`Read\`/\`Grep\`/\`Bash\` and the second one's input doesn't depend on the first's output, you should have done both in parallel.

## Waiting on async work — never use a fixed \`sleep\`

Whenever you need to wait for an async event — a build to finish, a dev server to boot, a HotSwap reload, a container to be healthy, a log line to appear, a file to be written, an HTTP endpoint to respond — **never use a fixed \`sleep N\` followed by a single check.** It wastes wall-clock when the condition is met early, and silently misses fast failures (the build broke in 1s but you slept 10s and only see "ERROR" if it's still in the last \`--tail 30\`).

Poll with a bounded loop, and match BOTH success and failure markers:

\`\`\`bash
for _ in $(seq 1 60); do
  docker logs --tail 50 mycontainer 2>&1 | grep -qE "READY|HotSwap done|FATAL|error:|BUILD FAILED" && break
  sleep 0.3
done
\`\`\`

This typically returns in well under a second when the work is done, and bails immediately on a failure marker. Keep the per-iteration sleep small (\`0.2\`–\`1.0\`) and the iteration count generous (\`30\`–\`120\`) so the upper bound covers your worst-case wait.

**Rule of thumb:** any \`sleep\` of 3 seconds or more *without* a polling loop around it is almost always wrong. If you can't think of a check command, you're probably waiting for nothing in particular — re-read what you actually need.

For env start / stop / rebuild specifically, prefer the \`wait_for_env_status\` MCP tool — it blocks server-side and is more efficient than rolling your own loop.

## Conversation so far in this session

This is a private chat session between ${speakerDisplay} and you. Cross-session bleed (team-wide knowledge) is handled separately in later context blocks. Prior turns within this session are kept in your conversation memory directly — each user message is prefixed with a markdown speaker block so you can tell who said what across turns.
${agentBlock}

## Filesystem memory mirror

A read-only markdown mirror of everything above (workspace + env knowledge, member profiles & memory, agent personas & skills) is materialized at \`.withvibe/memory/\` in your cwd. Use \`Read\` / \`Grep\` / \`Glob\` to search specific entries when you need exact text; start at \`.withvibe/memory/INDEX.md\`. **Writing files there has no effect** — the mirror is regenerated every turn from the database. To persist anything, use the \`save_*\` MCP tools.`;

    // Build the FS mirror for this turn. Always reflects the current workspace
    // + env; populates the speaker's memory and (for clone sessions) the
    // clone owner's memory as read-only.
    const disabledRowsForMirror = await phase(
      "mirror-fetch-env-disabled-agents",
      () =>
        this.prisma.client.envAgentDisabled.findMany({
          where: { envId },
          select: { agentId: true },
        })
    );
    const disabledForMirror = new Set(
      disabledRowsForMirror.map((r) => r.agentId)
    );
    const allWorkspaceAgents = await phase(
      "mirror-fetch-workspace-agents",
      () =>
        this.prisma.client.agent.findMany({
          where: { workspaceId: env.workspaceId },
          orderBy: [
            { pinned: "desc" },
            { position: "asc" },
            { createdAt: "asc" },
          ],
          select: {
            id: true,
            slug: true,
            name: true,
            description: true,
            systemPrompt: true,
            kind: true,
            cloneForUserId: true,
          },
        })
    );
    const enabledAgentsForMirror = allWorkspaceAgents.filter(
      (a) => !disabledForMirror.has(a.id)
    );
    const agentSkillsSummary: Record<
      string,
      Array<{ slug: string; name: string; description: string; scope: string }>
    > = {};
    await phase("mirror-fetch-agent-skills", async () => {
      for (const a of enabledAgentsForMirror) {
        agentSkillsSummary[a.id] =
          await this.prisma.client.agentSkill.findMany({
            where: {
              agentId: a.id,
              OR: [{ scope: "workspace" }, { scope: "env", envId }],
            },
            orderBy: { createdAt: "asc" },
            select: {
              slug: true,
              name: true,
              description: true,
              scope: true,
            },
          });
      }
    });
    await phase("mirror-materialize", () =>
      this.memoryMirror.materialize({
      envDir,
      workspace: {
        id: env.workspaceId,
        name: env.workspace.name,
        description: env.workspace.description,
      },
      env: {
        id: env.id,
        title: env.title,
        status: env.status,
        description: env.description,
      },
      speakerUserId,
      cloneOwnerUserId,
      members: members.map((m) => ({
        id: m.userId,
        name: m.user.name,
        email: m.user.email,
        positions: m.user.positions ?? [],
        bio: m.user.bio ?? null,
      })),
      enabledAgents: enabledAgentsForMirror,
      agentSkillsSummary,
      })
    );

    this.logger.info(
      `[ctx-build] TOTAL took ${Date.now() - buildStart}ms (env=${envId})`
    );

    return {
      systemAppend,
      speakerHeader,
      cwd: envDir,
      additionalDirectories: [
        ...readyRepos.map((r) => r.localPath),
        ...extraContext.map((c) => c.localPath),
      ],
      anthropicApiKey: env.workspace.anthropicApiKey ?? null,
      mcpServers,
      extraAllowedTools,
      disallowedTools,
      subagents,
      hasSkills,
      agent: agentConfig,
      debugMode: Boolean(env.workspace.debugMode),
      chatEngine: env.chatEngine,
      envModelChoice: env.modelChoice ?? null,
      workspaceDefaultModel: env.workspace.defaultModel ?? "auto",
      mcpBridgeToken: this.mcpTokens.sign({
        workspaceId: env.workspaceId,
        envId,
        userId: speakerUserId,
        sessionId,
        agentId: agentConfig?.agentId ?? null,
      }),
      envId,
      workspaceId: env.workspaceId,
      sessionId,
    };
  }
}
